function l = quadrotor_rcost(in1,in2)
%QUADROTOR_RCOST
%    L = QUADROTOR_RCOST(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    19-Sep-2023 10:47:31

a_sym1 = in1(1,:);
a_sym2 = in1(2,:);
a_sym3 = in1(3,:);
p_sym1 = in1(7,:);
p_sym2 = in1(8,:);
p_sym3 = in1(9,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
v_sym1 = in1(10,:);
v_sym2 = in1(11,:);
v_sym3 = in1(12,:);
w_sym1 = in1(4,:);
w_sym2 = in1(5,:);
w_sym3 = in1(6,:);
l = (u1.*conj(u1))./2.0e+2+(u2.*conj(u2))./2.0e+2+(u3.*conj(u3))./2.0e+2+(u4.*conj(u4))./2.0e+2+a_sym1.^2.*1.0e+1+a_sym2.^2.*1.0e+1+a_sym3.^2.*1.0e+1+p_sym1.^2.*1.0e+1+p_sym2.^2.*1.0e+1+p_sym3.^2.*1.0e+1+v_sym1.^2+v_sym2.^2+v_sym3.^2+w_sym1.^2.*1.0e+1+w_sym2.^2.*1.0e+1+w_sym3.^2.*1.0e+1;
