function l = pendulum_rcost(in1,u)
%PENDULUM_RCOST
%    L = PENDULUM_RCOST(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Apr-2023 12:09:44

x1 = in1(1,:);
l = u.^2.*(1.5e+1./2.0)+x1.^2./2.0e+1;
