function f = pendulum_dynamics(in1,u)
%PENDULUM_DYNAMICS
%    F = PENDULUM_DYNAMICS(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Apr-2023 12:09:44

x1 = in1(1,:);
x2 = in1(2,:);
f = [x1+x2./1.0e+1;u./1.0e+1+x2+sin(x1)./1.0e+1];
