function lf = pendulum_fcost(in1)
%PENDULUM_FCOST
%    LF = PENDULUM_FCOST(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Apr-2023 12:09:44

x1 = in1(1,:);
x2 = in1(2,:);
lf = x2.*(x1.*1.577814443074017e+4+x2.*1.576513273668194e+4)+x1.*(x1.*1.58174639622046e+4+x2.*1.577814443074017e+4);
