function [lf,qvf,Qf] = pendulum_fcost_quad_approx(in1)
%PENDULUM_FCOST_QUAD_APPROX
%    [LF,QVF,Qf] = PENDULUM_FCOST_QUAD_APPROX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    05-Apr-2023 12:09:44

x1 = in1(1,:);
x2 = in1(2,:);
lf = x2.*(x1.*1.577814443074017e+4+x2.*1.576513273668194e+4)+x1.*(x1.*1.58174639622046e+4+x2.*1.577814443074017e+4);
if nargout > 1
    qvf = [x1.*3.16349279244092e+4+x2.*3.155628886148035e+4;x1.*3.155628886148035e+4+x2.*3.153026547336388e+4];
end
if nargout > 2
    Qf = reshape([3.16349279244092e+4,3.155628886148035e+4,3.155628886148035e+4,3.153026547336388e+4],[2,2]);
end
