function [la,qav,Qa,rav,Ra,Sa] = acrobot_rcost_quad_approx_augment(in1,in2)
%ACROBOT_RCOST_QUAD_APPROX_AUGMENT
%    [LA,QAV,Qa,RAV,Ra,Sa] = ACROBOT_RCOST_QUAD_APPROX_AUGMENT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    08-Dec-2022 00:43:55

a1 = in2(2,:);
a2 = in2(3,:);
a3 = in2(4,:);
a4 = in2(5,:);
u = in2(1,:);
la = a1.^2.*1.0e+1+a2.^2.*1.0e+1+a3.^2.*1.0e+1+a4.^2.*1.0e+1+u.^2./4.0e+1;
if nargout > 1
    qav = [0.0;0.0;0.0;0.0];
end
if nargout > 2
    Qa = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
end
if nargout > 3
    rav = [u./2.0e+1;a1.*2.0e+1;a2.*2.0e+1;a3.*2.0e+1;a4.*2.0e+1];
end
if nargout > 4
    Ra = reshape([1.0./2.0e+1,0.0,0.0,0.0,0.0,0.0,2.0e+1,0.0,0.0,0.0,0.0,0.0,2.0e+1,0.0,0.0,0.0,0.0,0.0,2.0e+1,0.0,0.0,0.0,0.0,0.0,2.0e+1],[5,5]);
end
if nargout > 5
    Sa = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,4]);
end
