function l = acrobot_rcost(in1,u)
%ACROBOT_RCOST
%    L = ACROBOT_RCOST(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Oct-2023 22:15:46

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
l = u.^2./2.0e+2+x1.^2./2.0e+2+x2.^2./4.0e+2+x3.^2./4.0e+2+x4.^2./4.0e+2;
