function fa = acrobot_dynamics_augment(in1,in2)
%ACROBOT_DYNAMICS_AUGMENT
%    FA = ACROBOT_DYNAMICS_AUGMENT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    08-Dec-2022 00:43:55

a1 = in2(2,:);
a2 = in2(3,:);
a3 = in2(4,:);
a4 = in2(5,:);
u = in2(1,:);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x1);
t3 = cos(x2);
t4 = sin(x1);
t5 = sin(x2);
t6 = x3.^2;
t7 = x4.^2;
t8 = t3.^2;
t9 = t5.^2;
t10 = t5.^3;
t11 = t8.*3.3e+4;
t12 = t9.*1.33e+5;
t13 = t11+t12+4.4289e+4;
t14 = 1.0./t13;
et1 = t14;
et2 = t4.*6.52365e+5-u.*1.663e+5-t2.*t5.*3.26673e+5+t3.*t4.*1.63827e+5+t5.*t6.*1.663e+5-t2.*t10.*9.81e+5+t4.*t8.*3.2373e+5+t5.*t7.*1.33e+5+t4.*t9.*1.30473e+6+t6.*t10.*1.0e+5-t3.*u.*2.0e+5-t8.*u.*1.0e+5-t9.*u.*1.0e+5-t2.*t3.*t5.*9.81e+5+t3.*t5.*t6.*2.0e+5-t2.*t5.*t8.*9.81e+5+t3.*t5.*t7.*1.0e+5+t5.*t6.*t8.*1.0e+5+t5.*x3.*x4.*2.66e+5+t3.*t5.*x3.*x4.*2.0e+5;
et3 = -1.0./1.0e+2;
fa = [a1+x1+x3./1.0e+2;a2+x2+x4./1.0e+2;a3+x3+(t14.*(t4.*1.30473e+5-u.*2.66e+4+t5.*t6.*2.66e+4+t4.*t8.*6.4746e+4+t5.*t7.*2.66e+4+t4.*t9.*2.60946e+5-t3.*u.*2.0e+4-t2.*t3.*t5.*1.962e+5+t3.*t5.*t6.*2.0e+4+t5.*x3.*x4.*5.32e+4))./2.0e+1;a4+x4+et1.*et2.*et3];
