function [lf,qvf,Qf] = DP_fcost_quad_approx(in1)
%DP_fcost_quad_approx
%    [LF,QVF,Qf] = DP_fcost_quad_approx(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Oct-2023 22:01:36

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
lf = x1.^2.*5.0+x2.^2.*5.0+x3.^2.*5.0+x4.^2.*5.0;
if nargout > 1
    qvf = [x1.*1.0e+1;x2.*1.0e+1;x3.*1.0e+1;x4.*1.0e+1];
end
if nargout > 2
    Qf = reshape([1.0e+1,0.0,0.0,0.0,0.0,1.0e+1,0.0,0.0,0.0,0.0,1.0e+1,0.0,0.0,0.0,0.0,1.0e+1],[4,4]);
end
