function lf = DP_fcost(in1)
%DP_fcost
%    LF = DP_fcost(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Oct-2023 22:01:36

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
lf = x1.^2.*5.0+x2.^2.*5.0+x3.^2.*5.0+x4.^2.*5.0;
