function [l,qv,Q,rv,R,S] = DP_rcost_quad_approx(in1,u)
%DP_rcost_quad_approx
%    [L,QV,Q,RV,R,S] = DP_rcost_quad_approx(IN1,U)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Oct-2023 22:01:36

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
l = u.^2./2.0e+1+x1.^2./2.0e+3+x2.^2./2.0e+3+x3.^2./4.0e+3+x4.^2./4.0e+3;
if nargout > 1
    qv = [x1./1.0e+3;x2./1.0e+3;x3./2.0e+3;x4./2.0e+3];
end
if nargout > 2
    Q = reshape([1.0./1.0e+3,0.0,0.0,0.0,0.0,1.0./1.0e+3,0.0,0.0,0.0,0.0,5.0e-4,0.0,0.0,0.0,0.0,5.0e-4],[4,4]);
end
if nargout > 3
    rv = u./1.0e+1;
end
if nargout > 4
    R = 1.0./1.0e+1;
end
if nargout > 5
    S = [0.0,0.0,0.0,0.0];
end
